/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['.youtube-pic[_ngcontent-%COMP%] {\n 		position: relative;\n	}	\n .play-image[_ngcontent-%COMP%] {\n    width: 55px;\n    position: absolute;\n    left: 35%;\n    top: 35%;\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvb3JhbmdlL0Rlc2t0b3AvcHJvamVjdHMvbWFrZXIvbWFrZXItZnJvbnQtbmc0L3NyYy9hcHAvY29tcG9uZW50cy9sZWFybi9pbmRpdmlkdWFsLXdvcmtzaG9wL2luZGl2aWR1YWwtd29ya3Nob3AuY29tcG9uZW50LmNzcy5zaGltLm5nc3R5bGUudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9ob21lL29yYW5nZS9EZXNrdG9wL3Byb2plY3RzL21ha2VyL21ha2VyLWZyb250LW5nNC9zcmMvYXBwL2NvbXBvbmVudHMvbGVhcm4vaW5kaXZpZHVhbC13b3Jrc2hvcC9pbmRpdmlkdWFsLXdvcmtzaG9wLmNvbXBvbmVudC50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7In0=
