/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from './learn-routing.module';
import * as import2 from '@angular/router';
import * as import3 from './learn/learn.component.ngfactory';
import * as import4 from './individual-workshop/individual-workshop.component.ngfactory';
import * as import5 from './individual-workshop/single-object/single-object.component.ngfactory';
import * as import6 from './learn/learn.component';
import * as import7 from './individual-workshop/individual-workshop.component';
import * as import8 from './individual-workshop/single-object/single-object.component';
class LearnRoutingModuleInjector extends import0.ɵNgModuleInjector<import1.LearnRoutingModule> {
  _RouterModule_0:import2.RouterModule;
  _LearnRoutingModule_1:import1.LearnRoutingModule;
  _ROUTES_2:any[];
  constructor(parent:import0.Injector) {
    super(parent,[
      import3.LearnComponentNgFactory,
      import4.IndividualWorkshopComponentNgFactory,
      import5.SingleObjectComponentNgFactory
    ]
    ,([] as any[]));
  }
  createInternal():import1.LearnRoutingModule {
    this._RouterModule_0 = new import2.RouterModule(this.parent.get(import2.ɵa,(null as any)),this.parent.get(import2.Router,(null as any)));
    this._LearnRoutingModule_1 = new import1.LearnRoutingModule();
        this._ROUTES_2 = [[{
          path: '',
          children: [
            {
              path: '',
              component: import6.LearnComponent
            }
            ,
            {
              path: ':nid',
              component: import7.IndividualWorkshopComponent
            }
            ,
            {
              path: 'lessons/:workshopID/:nid',
              component: import8.SingleObjectComponent
            }

          ]

        }
    ]];
    return this._LearnRoutingModule_1;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.RouterModule)) { return this._RouterModule_0; }
    if ((token === import1.LearnRoutingModule)) { return this._LearnRoutingModule_1; }
    if ((token === import2.ROUTES)) { return this._ROUTES_2; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const LearnRoutingModuleNgFactory:import0.NgModuleFactory<import1.LearnRoutingModule> = new import0.NgModuleFactory<any>(LearnRoutingModuleInjector,import1.LearnRoutingModule);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvb3JhbmdlL0Rlc2t0b3AvcHJvamVjdHMvbWFrZXIvbWFrZXItZnJvbnQtbmc0L3NyYy9hcHAvY29tcG9uZW50cy9sZWFybi9sZWFybi1yb3V0aW5nLm1vZHVsZS5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9ob21lL29yYW5nZS9EZXNrdG9wL3Byb2plY3RzL21ha2VyL21ha2VyLWZyb250LW5nNC9zcmMvYXBwL2NvbXBvbmVudHMvbGVhcm4vbGVhcm4tcm91dGluZy5tb2R1bGUudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
