/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from './learn.module';
import * as import2 from '@angular/common';
import * as import3 from '@angular/router';
import * as import4 from './learn-routing.module';
import * as import5 from 'ng2-page-scroll/src/ng2-page-scroll.module';
import * as import6 from '@angular/forms';
import * as import7 from '@ng-bootstrap/ng-bootstrap/accordion/accordion.module';
import * as import8 from '@ng-bootstrap/ng-bootstrap/alert/alert.module';
import * as import9 from '@ng-bootstrap/ng-bootstrap/buttons/radio.module';
import * as import10 from '@ng-bootstrap/ng-bootstrap/carousel/carousel.module';
import * as import11 from '@ng-bootstrap/ng-bootstrap/collapse/collapse.module';
import * as import12 from '@ng-bootstrap/ng-bootstrap/datepicker/datepicker.module';
import * as import13 from '@ng-bootstrap/ng-bootstrap/dropdown/dropdown.module';
import * as import14 from '@ng-bootstrap/ng-bootstrap/modal/modal.module';
import * as import15 from '@ng-bootstrap/ng-bootstrap/pagination/pagination.module';
import * as import16 from '@ng-bootstrap/ng-bootstrap/popover/popover.module';
import * as import17 from '@ng-bootstrap/ng-bootstrap/progressbar/progressbar.module';
import * as import18 from '@ng-bootstrap/ng-bootstrap/rating/rating.module';
import * as import19 from '@ng-bootstrap/ng-bootstrap/tabset/tabset.module';
import * as import20 from '@ng-bootstrap/ng-bootstrap/timepicker/timepicker.module';
import * as import21 from '@ng-bootstrap/ng-bootstrap/tooltip/tooltip.module';
import * as import22 from '@ng-bootstrap/ng-bootstrap/typeahead/typeahead.module';
import * as import23 from '@ng-bootstrap/ng-bootstrap/index';
import * as import24 from '@angular/http';
import * as import25 from 'ngx-sharebuttons/share-buttons.module';
import * as import26 from 'ng2-responsive/index';
import * as import27 from '../shared/shared.module';
import * as import28 from '@ng-bootstrap/ng-bootstrap/modal/modal';
import * as import29 from 'ng2-responsive/config/config';
import * as import30 from 'ng2-page-scroll/src/ng2-page-scroll.service';
import * as import31 from './learn/learn.component.ngfactory';
import * as import32 from './individual-workshop/individual-workshop.component.ngfactory';
import * as import33 from './individual-workshop/single-object/single-object.component.ngfactory';
import * as import34 from '../../../../node_modules/@ng-bootstrap/ng-bootstrap/alert/alert.ngfactory';
import * as import35 from '../../../../node_modules/@ng-bootstrap/ng-bootstrap/datepicker/datepicker.ngfactory';
import * as import36 from '../../../../node_modules/@ng-bootstrap/ng-bootstrap/modal/modal-backdrop.ngfactory';
import * as import37 from '../../../../node_modules/@ng-bootstrap/ng-bootstrap/modal/modal-window.ngfactory';
import * as import38 from '../../../../node_modules/@ng-bootstrap/ng-bootstrap/popover/popover.ngfactory';
import * as import39 from '../../../../node_modules/@ng-bootstrap/ng-bootstrap/tooltip/tooltip.ngfactory';
import * as import40 from '../../../../node_modules/@ng-bootstrap/ng-bootstrap/typeahead/typeahead-window.ngfactory';
import * as import41 from '@ng-bootstrap/ng-bootstrap/modal/modal-stack';
import * as import42 from './learn/learn.component';
import * as import43 from './individual-workshop/individual-workshop.component';
import * as import44 from './individual-workshop/single-object/single-object.component';
class LearnModuleInjector extends import0.ɵNgModuleInjector<import1.LearnModule> {
  _CommonModule_0:import2.CommonModule;
  _RouterModule_1:import3.RouterModule;
  _LearnRoutingModule_2:import4.LearnRoutingModule;
  _Ng2PageScrollModule_3:import5.Ng2PageScrollModule;
  _ɵba_4:import6.ɵba;
  _FormsModule_5:import6.FormsModule;
  _ReactiveFormsModule_6:import6.ReactiveFormsModule;
  _NgbAccordionModule_7:import7.NgbAccordionModule;
  _NgbAlertModule_8:import8.NgbAlertModule;
  _NgbButtonsModule_9:import9.NgbButtonsModule;
  _NgbCarouselModule_10:import10.NgbCarouselModule;
  _NgbCollapseModule_11:import11.NgbCollapseModule;
  _NgbDatepickerModule_12:import12.NgbDatepickerModule;
  _NgbDropdownModule_13:import13.NgbDropdownModule;
  _NgbModalModule_14:import14.NgbModalModule;
  _NgbPaginationModule_15:import15.NgbPaginationModule;
  _NgbPopoverModule_16:import16.NgbPopoverModule;
  _NgbProgressbarModule_17:import17.NgbProgressbarModule;
  _NgbRatingModule_18:import18.NgbRatingModule;
  _NgbTabsetModule_19:import19.NgbTabsetModule;
  _NgbTimepickerModule_20:import20.NgbTimepickerModule;
  _NgbTooltipModule_21:import21.NgbTooltipModule;
  _NgbTypeaheadModule_22:import22.NgbTypeaheadModule;
  _NgbModule_23:import23.NgbModule;
  _JsonpModule_24:import24.JsonpModule;
  _ShareButtonsModule_25:import25.ShareButtonsModule;
  _ResponsiveModule_26:import26.ResponsiveModule;
  _SharedModule_27:import27.SharedModule;
  _LearnModule_28:import1.LearnModule;
  __NgLocalization_29:import2.NgLocaleLocalization;
  _ROUTES_30:any[];
  __ɵi_31:import6.ɵi;
  __FormBuilder_32:import6.FormBuilder;
  __NgbModal_33:import28.NgbModal;
  __ɵg_34:import24.ɵg;
  __ResponseOptions_35:import24.BaseResponseOptions;
  __JSONPBackend_36:import24.ɵa;
  __RequestOptions_37:import24.BaseRequestOptions;
  __Jsonp_38:any;
  __ResponsiveConfig_39:import29.ResponsiveConfig;
  __ResponsiveState_40:import29.ResponsiveState;
  __PageScrollService_41:import30.PageScrollService;
  constructor(parent:import0.Injector) {
    super(parent,[
      import31.LearnComponentNgFactory,
      import32.IndividualWorkshopComponentNgFactory,
      import33.SingleObjectComponentNgFactory,
      import34.NgbAlertNgFactory,
      import35.NgbDatepickerNgFactory,
      import36.NgbModalBackdropNgFactory,
      import37.NgbModalWindowNgFactory,
      import38.NgbPopoverWindowNgFactory,
      import39.NgbTooltipWindowNgFactory,
      import40.NgbTypeaheadWindowNgFactory
    ]
    ,([] as any[]));
  }
  get _NgLocalization_29():import2.NgLocaleLocalization {
    if ((this.__NgLocalization_29 == null)) { (this.__NgLocalization_29 = new import2.NgLocaleLocalization(this.parent.get(import0.LOCALE_ID))); }
    return this.__NgLocalization_29;
  }
  get _ɵi_31():import6.ɵi {
    if ((this.__ɵi_31 == null)) { (this.__ɵi_31 = new import6.ɵi()); }
    return this.__ɵi_31;
  }
  get _FormBuilder_32():import6.FormBuilder {
    if ((this.__FormBuilder_32 == null)) { (this.__FormBuilder_32 = new import6.FormBuilder()); }
    return this.__FormBuilder_32;
  }
  get _NgbModal_33():import28.NgbModal {
    if ((this.__NgbModal_33 == null)) { (this.__NgbModal_33 = new import28.NgbModal(this.componentFactoryResolver,this,this.parent.get(import41.NgbModalStack))); }
    return this.__NgbModal_33;
  }
  get _ɵg_34():import24.ɵg {
    if ((this.__ɵg_34 == null)) { (this.__ɵg_34 = new import24.ɵg()); }
    return this.__ɵg_34;
  }
  get _ResponseOptions_35():import24.BaseResponseOptions {
    if ((this.__ResponseOptions_35 == null)) { (this.__ResponseOptions_35 = new import24.BaseResponseOptions()); }
    return this.__ResponseOptions_35;
  }
  get _JSONPBackend_36():import24.ɵa {
    if ((this.__JSONPBackend_36 == null)) { (this.__JSONPBackend_36 = new import24.ɵa(this._ɵg_34,this._ResponseOptions_35)); }
    return this.__JSONPBackend_36;
  }
  get _RequestOptions_37():import24.BaseRequestOptions {
    if ((this.__RequestOptions_37 == null)) { (this.__RequestOptions_37 = new import24.BaseRequestOptions()); }
    return this.__RequestOptions_37;
  }
  get _Jsonp_38():any {
    if ((this.__Jsonp_38 == null)) { (this.__Jsonp_38 = import24.ɵd(this._JSONPBackend_36,this._RequestOptions_37)); }
    return this.__Jsonp_38;
  }
  get _ResponsiveConfig_39():import29.ResponsiveConfig {
    if ((this.__ResponsiveConfig_39 == null)) { (this.__ResponsiveConfig_39 = new import29.ResponsiveConfig(this.parent.get(import29.ResponsiveConfigInterface,(null as any)))); }
    return this.__ResponsiveConfig_39;
  }
  get _ResponsiveState_40():import29.ResponsiveState {
    if ((this.__ResponsiveState_40 == null)) { (this.__ResponsiveState_40 = new import29.ResponsiveState(this._ResponsiveConfig_39)); }
    return this.__ResponsiveState_40;
  }
  get _PageScrollService_41():import30.PageScrollService {
    if ((this.__PageScrollService_41 == null)) { (this.__PageScrollService_41 = new import30.PageScrollService()); }
    return this.__PageScrollService_41;
  }
  createInternal():import1.LearnModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._RouterModule_1 = new import3.RouterModule(this.parent.get(import3.ɵa,(null as any)),this.parent.get(import3.Router,(null as any)));
    this._LearnRoutingModule_2 = new import4.LearnRoutingModule();
    this._Ng2PageScrollModule_3 = new import5.Ng2PageScrollModule();
    this._ɵba_4 = new import6.ɵba();
    this._FormsModule_5 = new import6.FormsModule();
    this._ReactiveFormsModule_6 = new import6.ReactiveFormsModule();
    this._NgbAccordionModule_7 = new import7.NgbAccordionModule();
    this._NgbAlertModule_8 = new import8.NgbAlertModule();
    this._NgbButtonsModule_9 = new import9.NgbButtonsModule();
    this._NgbCarouselModule_10 = new import10.NgbCarouselModule();
    this._NgbCollapseModule_11 = new import11.NgbCollapseModule();
    this._NgbDatepickerModule_12 = new import12.NgbDatepickerModule();
    this._NgbDropdownModule_13 = new import13.NgbDropdownModule();
    this._NgbModalModule_14 = new import14.NgbModalModule();
    this._NgbPaginationModule_15 = new import15.NgbPaginationModule();
    this._NgbPopoverModule_16 = new import16.NgbPopoverModule();
    this._NgbProgressbarModule_17 = new import17.NgbProgressbarModule();
    this._NgbRatingModule_18 = new import18.NgbRatingModule();
    this._NgbTabsetModule_19 = new import19.NgbTabsetModule();
    this._NgbTimepickerModule_20 = new import20.NgbTimepickerModule();
    this._NgbTooltipModule_21 = new import21.NgbTooltipModule();
    this._NgbTypeaheadModule_22 = new import22.NgbTypeaheadModule();
    this._NgbModule_23 = new import23.NgbModule();
    this._JsonpModule_24 = new import24.JsonpModule();
    this._ShareButtonsModule_25 = new import25.ShareButtonsModule();
    this._ResponsiveModule_26 = new import26.ResponsiveModule();
    this._SharedModule_27 = new import27.SharedModule();
    this._LearnModule_28 = new import1.LearnModule();
        this._ROUTES_30 = [[{
          path: '',
          children: [
            {
              path: '',
              component: import42.LearnComponent
            }
            ,
            {
              path: ':nid',
              component: import43.IndividualWorkshopComponent
            }
            ,
            {
              path: 'lessons/:workshopID/:nid',
              component: import44.SingleObjectComponent
            }

          ]

        }
    ]];
    return this._LearnModule_28;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import3.RouterModule)) { return this._RouterModule_1; }
    if ((token === import4.LearnRoutingModule)) { return this._LearnRoutingModule_2; }
    if ((token === import5.Ng2PageScrollModule)) { return this._Ng2PageScrollModule_3; }
    if ((token === import6.ɵba)) { return this._ɵba_4; }
    if ((token === import6.FormsModule)) { return this._FormsModule_5; }
    if ((token === import6.ReactiveFormsModule)) { return this._ReactiveFormsModule_6; }
    if ((token === import7.NgbAccordionModule)) { return this._NgbAccordionModule_7; }
    if ((token === import8.NgbAlertModule)) { return this._NgbAlertModule_8; }
    if ((token === import9.NgbButtonsModule)) { return this._NgbButtonsModule_9; }
    if ((token === import10.NgbCarouselModule)) { return this._NgbCarouselModule_10; }
    if ((token === import11.NgbCollapseModule)) { return this._NgbCollapseModule_11; }
    if ((token === import12.NgbDatepickerModule)) { return this._NgbDatepickerModule_12; }
    if ((token === import13.NgbDropdownModule)) { return this._NgbDropdownModule_13; }
    if ((token === import14.NgbModalModule)) { return this._NgbModalModule_14; }
    if ((token === import15.NgbPaginationModule)) { return this._NgbPaginationModule_15; }
    if ((token === import16.NgbPopoverModule)) { return this._NgbPopoverModule_16; }
    if ((token === import17.NgbProgressbarModule)) { return this._NgbProgressbarModule_17; }
    if ((token === import18.NgbRatingModule)) { return this._NgbRatingModule_18; }
    if ((token === import19.NgbTabsetModule)) { return this._NgbTabsetModule_19; }
    if ((token === import20.NgbTimepickerModule)) { return this._NgbTimepickerModule_20; }
    if ((token === import21.NgbTooltipModule)) { return this._NgbTooltipModule_21; }
    if ((token === import22.NgbTypeaheadModule)) { return this._NgbTypeaheadModule_22; }
    if ((token === import23.NgbModule)) { return this._NgbModule_23; }
    if ((token === import24.JsonpModule)) { return this._JsonpModule_24; }
    if ((token === import25.ShareButtonsModule)) { return this._ShareButtonsModule_25; }
    if ((token === import26.ResponsiveModule)) { return this._ResponsiveModule_26; }
    if ((token === import27.SharedModule)) { return this._SharedModule_27; }
    if ((token === import1.LearnModule)) { return this._LearnModule_28; }
    if ((token === import2.NgLocalization)) { return this._NgLocalization_29; }
    if ((token === import3.ROUTES)) { return this._ROUTES_30; }
    if ((token === import6.ɵi)) { return this._ɵi_31; }
    if ((token === import6.FormBuilder)) { return this._FormBuilder_32; }
    if ((token === import28.NgbModal)) { return this._NgbModal_33; }
    if ((token === import24.ɵg)) { return this._ɵg_34; }
    if ((token === import24.ResponseOptions)) { return this._ResponseOptions_35; }
    if ((token === import24.JSONPBackend)) { return this._JSONPBackend_36; }
    if ((token === import24.RequestOptions)) { return this._RequestOptions_37; }
    if ((token === import24.Jsonp)) { return this._Jsonp_38; }
    if ((token === import29.ResponsiveConfig)) { return this._ResponsiveConfig_39; }
    if ((token === import29.ResponsiveState)) { return this._ResponsiveState_40; }
    if ((token === import30.PageScrollService)) { return this._PageScrollService_41; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const LearnModuleNgFactory:import0.NgModuleFactory<import1.LearnModule> = new import0.NgModuleFactory<any>(LearnModuleInjector,import1.LearnModule);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvb3JhbmdlL0Rlc2t0b3AvcHJvamVjdHMvbWFrZXIvbWFrZXItZnJvbnQtbmc0L3NyYy9hcHAvY29tcG9uZW50cy9sZWFybi9sZWFybi5tb2R1bGUubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vaG9tZS9vcmFuZ2UvRGVza3RvcC9wcm9qZWN0cy9tYWtlci9tYWtlci1mcm9udC1uZzQvc3JjL2FwcC9jb21wb25lbnRzL2xlYXJuL2xlYXJuLm1vZHVsZS50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
