/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '@angular/common';
import * as import2 from './report-comment.component';
import * as import3 from '../../../d7services/view/view.service';
import * as import4 from '@angular/router';
import * as import5 from '../../../d7services/user/user.service';
import * as import6 from '../../../d7services/flag/flag.service';
import * as import7 from 'angular2-notification-bar/release/src/notification-bar.service';
const styles_ReportCommentComponent:any[] = ([] as any[]);
export const RenderType_ReportCommentComponent:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_ReportCommentComponent,
  data: {}
}
);
function View_ReportCommentComponent_1(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
      (l()(),import0.ɵeld(0,(null as any),(null as any),2,'a',[[
        'class',
        'report'
      ]
      ],(null as any),[[
        (null as any),
        'click'
      ]
    ],(v,en,$event) => {
      var ad:boolean = true;
      var co:any = v.component;
      if (('click' === en)) {
        const pd_0:any = ((<any>co.onSubmit($event)) !== false);
        ad = (pd_0 && ad);
      }
      return ad;
    },(null as any),(null as any))),
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'p',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['Report this Feedback']))
  ]
  ,(null as any),(null as any));
}
function View_ReportCommentComponent_2(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'p',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),[' comment has been reported ']))
  ]
  ,(null as any),(null as any));
}
export function View_ReportCommentComponent_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
      (l()(),import0.ɵeld(0,(null as any),(null as any),7,'div',[[
        'class',
        'report'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['\n  '])),
    (l()(),import0.ɵand(16777216,(null as any),(null as any),1,(null as any),View_ReportCommentComponent_1)),
    import0.ɵdid(16384,(null as any),0,import1.NgIf,[
      import0.ViewContainerRef,
      import0.TemplateRef
    ]
      ,{ngIf: [
        0,
        'ngIf'
      ]
    },(null as any)),
    (l()(),import0.ɵted((null as any),['\n  '])),
    (l()(),import0.ɵand(16777216,(null as any),(null as any),1,(null as any),View_ReportCommentComponent_2)),
    import0.ɵdid(16384,(null as any),0,import1.NgIf,[
      import0.ViewContainerRef,
      import0.TemplateRef
    ]
      ,{ngIf: [
        0,
        'ngIf'
      ]
    },(null as any)),
    (l()(),import0.ɵted((null as any),['\n']))
  ]
  ,(ck,v) => {
    var co:import2.ReportCommentComponent = v.component;
    const currVal_0:boolean = !co.isReported;
    ck(v,3,0,currVal_0);
    const currVal_1:any = co.isReported;
    ck(v,6,0,currVal_1);
  },(null as any));
}
function View_ReportCommentComponent_Host_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'app-report-comment',([] as any[]),(null as any),(null as any),(null as any),View_ReportCommentComponent_0,RenderType_ReportCommentComponent)),
    import0.ɵdid(114688,(null as any),0,import2.ReportCommentComponent,[
      import3.ViewService,
      import4.Router,
      import5.UserService,
      import6.FlagService,
      import7.NotificationBarService
    ]
    ,(null as any),(null as any))
  ]
  ,(ck,v) => {
    ck(v,1,0);
  },(null as any));
}
export const ReportCommentComponentNgFactory:import0.ComponentFactory<import2.ReportCommentComponent> = import0.ɵccf('app-report-comment',import2.ReportCommentComponent,View_ReportCommentComponent_Host_0,{commentReportId: 'commentReportId'},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvb3JhbmdlL0Rlc2t0b3AvcHJvamVjdHMvbWFrZXIvbWFrZXItZnJvbnQtbmc0L3NyYy9hcHAvY29tcG9uZW50cy9zaGFyZWQvcmVwb3J0LWNvbW1lbnQvcmVwb3J0LWNvbW1lbnQuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL2hvbWUvb3JhbmdlL0Rlc2t0b3AvcHJvamVjdHMvbWFrZXIvbWFrZXItZnJvbnQtbmc0L3NyYy9hcHAvY29tcG9uZW50cy9zaGFyZWQvcmVwb3J0LWNvbW1lbnQvcmVwb3J0LWNvbW1lbnQuY29tcG9uZW50LnRzIiwibmc6Ly8vaG9tZS9vcmFuZ2UvRGVza3RvcC9wcm9qZWN0cy9tYWtlci9tYWtlci1mcm9udC1uZzQvc3JjL2FwcC9jb21wb25lbnRzL3NoYXJlZC9yZXBvcnQtY29tbWVudC9yZXBvcnQtY29tbWVudC5jb21wb25lbnQuaHRtbCIsIm5nOi8vL2hvbWUvb3JhbmdlL0Rlc2t0b3AvcHJvamVjdHMvbWFrZXIvbWFrZXItZnJvbnQtbmc0L3NyYy9hcHAvY29tcG9uZW50cy9zaGFyZWQvcmVwb3J0LWNvbW1lbnQvcmVwb3J0LWNvbW1lbnQuY29tcG9uZW50LnRzLlJlcG9ydENvbW1lbnRDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCI8ZGl2IGNsYXNzPVwicmVwb3J0XCI+XG4gIDxhIGNsYXNzPVwicmVwb3J0XCIgKm5nSWY9XCIhaXNSZXBvcnRlZFwiIChjbGljayk9XCJvblN1Ym1pdCgkZXZlbnQpXCI+PHA+UmVwb3J0IHRoaXMgRmVlZGJhY2s8L3A+PC9hPlxuICA8cCAqbmdJZj1cImlzUmVwb3J0ZWRcIj4gY29tbWVudCBoYXMgYmVlbiByZXBvcnRlZCA8L3A+XG48L2Rpdj4iLCI8YXBwLXJlcG9ydC1jb21tZW50PjwvYXBwLXJlcG9ydC1jb21tZW50PiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7TUNDRTtRQUFBO1FBQUE7TUFBQTtNQUFBO1FBQUE7UUFBQTtNQUFBO0lBQUE7TUFBQTtNQUFBO01BQXNDO1FBQUE7UUFBQTtNQUFBO01BQXRDO0lBQUE7SUFBaUU7SUFBRzs7Ozs7O0lBQ3BFO0lBQXNCOzs7Ozs7TUFGeEI7UUFBQTtRQUFBO01BQUE7SUFBQTtJQUFvQjtJQUNsQjtnQkFBQTs7O0lBQUE7T0FBQTtRQUFBO1FBQUE7TUFBQTtJQUFBO0lBQWdHO0lBQ2hHO2dCQUFBOzs7SUFBQTtPQUFBO1FBQUE7UUFBQTtNQUFBO0lBQUE7SUFBcUQ7Ozs7SUFEbkM7SUFBbEIsU0FBa0IsU0FBbEI7SUFDRztJQUFILFNBQUcsU0FBSDs7Ozs7SUNGRjtnQkFBQTs7Ozs7O0lBQUE7S0FBQTs7O0lBQUE7OzsifQ==
