/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from './showcase-project-routing.module';
import * as import2 from '@angular/router';
import * as import3 from './showcase-project.component.ngfactory';
import * as import4 from './showcase-project.component';
class ShowcaseProjectRoutingModuleInjector extends import0.ɵNgModuleInjector<import1.ShowcaseProjectRoutingModule> {
  _RouterModule_0:import2.RouterModule;
  _ShowcaseProjectRoutingModule_1:import1.ShowcaseProjectRoutingModule;
  _ROUTES_2:any[];
  constructor(parent:import0.Injector) {
    super(parent,[import3.ShowcaseProjectComponentNgFactory],([] as any[]));
  }
  createInternal():import1.ShowcaseProjectRoutingModule {
    this._RouterModule_0 = new import2.RouterModule(this.parent.get(import2.ɵa,(null as any)),this.parent.get(import2.Router,(null as any)));
    this._ShowcaseProjectRoutingModule_1 = new import1.ShowcaseProjectRoutingModule();
        this._ROUTES_2 = [[{
          path: '',
          component: import4.ShowcaseProjectComponent
        }
    ]];
    return this._ShowcaseProjectRoutingModule_1;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.RouterModule)) { return this._RouterModule_0; }
    if ((token === import1.ShowcaseProjectRoutingModule)) { return this._ShowcaseProjectRoutingModule_1; }
    if ((token === import2.ROUTES)) { return this._ROUTES_2; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const ShowcaseProjectRoutingModuleNgFactory:import0.NgModuleFactory<import1.ShowcaseProjectRoutingModule> = new import0.NgModuleFactory<any>(ShowcaseProjectRoutingModuleInjector,import1.ShowcaseProjectRoutingModule);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvb3JhbmdlL0Rlc2t0b3AvcHJvamVjdHMvbWFrZXIvbWFrZXItZnJvbnQtbmc0L3NyYy9hcHAvY29tcG9uZW50cy9zaG93Y2FzZS9zaG93Y2FzZS1wcm9qZWN0L3Nob3djYXNlLXByb2plY3Qtcm91dGluZy5tb2R1bGUubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vaG9tZS9vcmFuZ2UvRGVza3RvcC9wcm9qZWN0cy9tYWtlci9tYWtlci1mcm9udC1uZzQvc3JjL2FwcC9jb21wb25lbnRzL3Nob3djYXNlL3Nob3djYXNlLXByb2plY3Qvc2hvd2Nhc2UtcHJvamVjdC1yb3V0aW5nLm1vZHVsZS50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
