/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from './showcase-routing.module';
import * as import2 from '@angular/router';
import * as import3 from './showcase-collection/showcasesCollection.component.ngfactory';
import * as import4 from './single-showcase/SingleShowcase.component.ngfactory';
import * as import5 from './showcase-project/showcase-project.component.ngfactory';
import * as import6 from './showcase-collection/showcasesCollection.component';
import * as import7 from './single-showcase/SingleShowcase.component';
import * as import8 from './showcase-project/showcase-project.component';
class ShowcaseRoutingModuleInjector extends import0.ɵNgModuleInjector<import1.ShowcaseRoutingModule> {
  _RouterModule_0:import2.RouterModule;
  _ShowcaseRoutingModule_1:import1.ShowcaseRoutingModule;
  _ROUTES_2:any[];
  constructor(parent:import0.Injector) {
    super(parent,[
      import3.ShowcasesCollectionComponentNgFactory,
      import4.SinglShowcaseComponentNgFactory,
      import5.ShowcaseProjectComponentNgFactory
    ]
    ,([] as any[]));
  }
  createInternal():import1.ShowcaseRoutingModule {
    this._RouterModule_0 = new import2.RouterModule(this.parent.get(import2.ɵa,(null as any)),this.parent.get(import2.Router,(null as any)));
    this._ShowcaseRoutingModule_1 = new import1.ShowcaseRoutingModule();
        this._ROUTES_2 = [[{
          path: '',
          children: [
            {
              path: '',
              component: import6.ShowcasesCollectionComponent
            }
            ,
            {
              path: ':path',
              component: import7.SinglShowcaseComponent
            }
            ,
            {
              path: 'project2/:nid/:sort1/:sort2/:pnid',
              component: import8.ShowcaseProjectComponent
            }

          ]

        }
    ]];
    return this._ShowcaseRoutingModule_1;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.RouterModule)) { return this._RouterModule_0; }
    if ((token === import1.ShowcaseRoutingModule)) { return this._ShowcaseRoutingModule_1; }
    if ((token === import2.ROUTES)) { return this._ROUTES_2; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const ShowcaseRoutingModuleNgFactory:import0.NgModuleFactory<import1.ShowcaseRoutingModule> = new import0.NgModuleFactory<any>(ShowcaseRoutingModuleInjector,import1.ShowcaseRoutingModule);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvb3JhbmdlL0Rlc2t0b3AvcHJvamVjdHMvbWFrZXIvbWFrZXItZnJvbnQtbmc0L3NyYy9hcHAvY29tcG9uZW50cy9zaG93Y2FzZS9zaG93Y2FzZS1yb3V0aW5nLm1vZHVsZS5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9ob21lL29yYW5nZS9EZXNrdG9wL3Byb2plY3RzL21ha2VyL21ha2VyLWZyb250LW5nNC9zcmMvYXBwL2NvbXBvbmVudHMvc2hvd2Nhc2Uvc2hvd2Nhc2Utcm91dGluZy5tb2R1bGUudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
