/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from './project-form-routing.module';
import * as import2 from '@angular/router';
import * as import3 from './project-form/project-form.component.ngfactory';
import * as import4 from './project-form/project-form.component';
import * as import5 from '../../../auth0/auth-guard.service';
import * as import6 from './pending-changes.guard';
class ProjectFormRoutingModuleInjector extends import0.ɵNgModuleInjector<import1.ProjectFormRoutingModule> {
  _RouterModule_0:import2.RouterModule;
  _ProjectFormRoutingModule_1:import1.ProjectFormRoutingModule;
  _ROUTES_2:any[];
  constructor(parent:import0.Injector) {
    super(parent,[import3.ProjectFormComponentNgFactory],([] as any[]));
  }
  createInternal():import1.ProjectFormRoutingModule {
    this._RouterModule_0 = new import2.RouterModule(this.parent.get(import2.ɵa,(null as any)),this.parent.get(import2.Router,(null as any)));
    this._ProjectFormRoutingModule_1 = new import1.ProjectFormRoutingModule();
      this._ROUTES_2 = [[
        {
          path: '',
          component: import4.ProjectFormComponent,
          canActivate: [import5.AuthGuardService],
          canDeactivate: [import6.PendingChangesGuard]
        }
        ,
        {
          path: ':path/edit',
          component: import4.ProjectFormComponent,
          canActivate: [import5.AuthGuardService],
          canDeactivate: [import6.PendingChangesGuard]
        }

      ]
    ];
    return this._ProjectFormRoutingModule_1;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.RouterModule)) { return this._RouterModule_0; }
    if ((token === import1.ProjectFormRoutingModule)) { return this._ProjectFormRoutingModule_1; }
    if ((token === import2.ROUTES)) { return this._ROUTES_2; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const ProjectFormRoutingModuleNgFactory:import0.NgModuleFactory<import1.ProjectFormRoutingModule> = new import0.NgModuleFactory<any>(ProjectFormRoutingModuleInjector,import1.ProjectFormRoutingModule);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvb3JhbmdlL0Rlc2t0b3AvcHJvamVjdHMvbWFrZXIvbWFrZXItZnJvbnQtbmc0L3NyYy9hcHAvY29tcG9uZW50cy9wcm9qZWN0cy9wcm9qZWN0LWZvcm0vcHJvamVjdC1mb3JtLXJvdXRpbmcubW9kdWxlLm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL2hvbWUvb3JhbmdlL0Rlc2t0b3AvcHJvamVjdHMvbWFrZXIvbWFrZXItZnJvbnQtbmc0L3NyYy9hcHAvY29tcG9uZW50cy9wcm9qZWN0cy9wcm9qZWN0LWZvcm0vcHJvamVjdC1mb3JtLXJvdXRpbmcubW9kdWxlLnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzsifQ==
