/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['#search-box-layer[_ngcontent-%COMP%] {\n  position: fixed;\n  z-index: 1000;\n  background: rgba(25,25,25,0.9);\n  width: 100%;\n  height: 100%;\n  left: 0;\n  top: 0;\n}\n\n.close-search-layer[_ngcontent-%COMP%] {\n    float: right;\n    color: white;\n    font-size: 30px;\n    margin-right: 20px;\n    margin-top: 20px;\n}\n\n#search-box-form[_ngcontent-%COMP%] {\nmargin-top: 180px;\n}\n\n#search-box-form[_ngcontent-%COMP%]   h3[_ngcontent-%COMP%]{\n  color: white;\n  font-size: 38px; \n}\n\n#search-box-input[_ngcontent-%COMP%] {\n    width: 100%;\n    color: white;\n    background: transparent;\n    border: 0 none;\n    border-bottom: 1px solid white;\n    padding: 10px;\n}\n\n.search-form-group[_ngcontent-%COMP%] {\n    position: relative;\n    max-width: 100%;\n    margin-top: 20px;\n    width: 400px;\n    display: block;\n    margin-right: auto;\n    margin-left: auto;\n}\n.go-search[_ngcontent-%COMP%] {\n    color: white;\n    font-size: 30px;\n    position: absolute;\n    top: 0px;\n    right: 0px;\n    cursor: pointer;\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvb3JhbmdlL0Rlc2t0b3AvcHJvamVjdHMvbWFrZXIvbWFrZXItZnJvbnQtbmc0L3NyYy9hcHAvY29tcG9uZW50cy9nZW5lcmFsL2hlYWRlci9zZWFyY2gtYm94L3NlYXJjaC1ib3guY29tcG9uZW50LmNzcy5zaGltLm5nc3R5bGUudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9ob21lL29yYW5nZS9EZXNrdG9wL3Byb2plY3RzL21ha2VyL21ha2VyLWZyb250LW5nNC9zcmMvYXBwL2NvbXBvbmVudHMvZ2VuZXJhbC9oZWFkZXIvc2VhcmNoLWJveC9zZWFyY2gtYm94LmNvbXBvbmVudC50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7In0=
